#pragma once

// Wi-Fi 1（優先連線）
#define WIFI_1_SSID "YOUR_WIFI_SSID_1"
#define WIFI_1_PASSWORD "YOUR_WIFI_PASSWORD_1"

// Wi-Fi 2（Wi-Fi 1 失敗時改用）
#define WIFI_2_SSID "YOUR_WIFI_SSID_2"
#define WIFI_2_PASSWORD "YOUR_WIFI_PASSWORD_2"

// 每組 Wi-Fi 最長等待時間（毫秒）
#define WIFI_CONNECT_TIMEOUT_MS 10000
#define WIFI_NO_SSID_FAIL_MS 2500
#define WIFI_RETRY_INTERVAL_MS 15000
