#!/usr/bin/env python3
"""Fetch HKO tc weather text and regenerate tools/hko_font_codes.h."""

import json
import subprocess
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent
COMMON_CHARS_FILE = ROOT / "common_traditional_chars.txt"
CREATE_FONT_PDE = ROOT / "Create_font" / "Create_font.pde"

UI_TEXT = (
    "香港天文台 京士柏 連線中 Wi-Fi 失敗 無法連線 啟動中 正在連線 "
    "請檢查訊號/密碼 天氣資料 正在更新天氣 暫時無法取得本港天氣預測 "
    "溫度 濕度 紫外線 更新 天文台"
)
EXTRA_TEXT = "颱颱暴雨雷暴寒冷酷熱火球警告訊號預報本港各區大致多雲°C"


def load_common_chars() -> str:
    if not COMMON_CHARS_FILE.exists():
        return ""
    text = []
    for line in COMMON_CHARS_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        text.append(line)
    return "".join(text)


def fetch_json(url: str) -> object:
    try:
        with urllib.request.urlopen(url, timeout=20) as response:
            return json.loads(response.read().decode("utf-8"))
    except Exception:
        result = subprocess.run(
            ["curl", "-sk", url],
            check=True,
            capture_output=True,
            text=True,
        )
        return json.loads(result.stdout)


def walk(value, chars: set[str]) -> None:
    if isinstance(value, str):
        chars.update(value)
    elif isinstance(value, dict):
        for item in value.values():
            walk(item, chars)
    elif isinstance(value, list):
        for item in value:
            walk(item, chars)


def write_processing_header(codes: list[int]) -> None:
    lines = [f"  0x{code:04X}," for code in codes]
    header = (
        "// Auto-generated by tools/generate_hko_font_codes.py\n"
        "static final int[] specificUnicodes = {\n"
        + "\n".join(lines)
        + "\n};\n"
    )
    (ROOT / "hko_font_codes.h").write_text(header, encoding="utf-8")

    if not CREATE_FONT_PDE.exists():
        return

    pde = CREATE_FONT_PDE.read_text(encoding="utf-8")
    start = pde.index("static final int[] unicodeBlocks")
    end = pde.index("// >>>>>>>>>> USER CONFIGURED PARAMETERS END HERE")
    replacement = (
        "static final int[] unicodeBlocks = {\n"
        "  0x0021, 0x007E, // ASCII\n"
        "};\n\n"
        + header
        + "\n"
    )
    CREATE_FONT_PDE.write_text(pde[:start] + replacement + pde[end:], encoding="utf-8")


def main() -> None:
    chars = set(UI_TEXT + EXTRA_TEXT + load_common_chars())
    base = "https://data.weather.gov.hk/weatherAPI/opendata/weather.php"
    for data_type in ("rhrread", "flw", "fnd", "warnsum"):
        walk(fetch_json(f"{base}?dataType={data_type}&lang=tc"), chars)

    codes = sorted({ord(ch) for ch in chars if ord(ch) >= 0x20})
    write_processing_header(codes)
    (ROOT / "hko_font_chars.txt").write_text("".join(sorted(chars)), encoding="utf-8")
    print(f"Wrote {len(codes)} code points to {ROOT / 'hko_font_codes.h'}")
    if CREATE_FONT_PDE.exists():
        print(f"Updated {CREATE_FONT_PDE}")


if __name__ == "__main__":
    main()
