#!/usr/bin/env python3
"""Fetch HKO tc weather text and regenerate font unicode tables for Processing."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import urllib.request
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = TOOLS_DIR.parent
COMMON_CHARS_FILE = TOOLS_DIR / "common_traditional_chars.txt"
DETAIL_CHARS_FILE = TOOLS_DIR / "common_traditional_chars_detail.txt"
CREATE_FONT_PDE = TOOLS_DIR / "Create_font" / "Create_font.pde"
OPENCC_ST_URL = (
    "https://raw.githubusercontent.com/BYVoid/OpenCC/master/data/dictionary/STCharacters.txt"
)
HKO_API = "https://data.weather.gov.hk/weatherAPI/opendata/weather.php"
HKO_DATA_TYPES = ("rhrread", "flw", "fnd", "warnsum", "warningInfo")
FIRMWARE_SCAN_DIRS = (PROJECT_ROOT / "src", PROJECT_ROOT / "include")
STRING_LITERAL_RE = re.compile(r'"([^"\\]*(?:\\.[^"\\]*)*)"')


def load_chars_file(path: Path) -> str:
    if not path.exists():
        return ""
    chunks: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            chunks.append(line)
    return "".join(chunks)


def fetch_url(url: str, *, timeout: int = 30) -> str:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as response:
            return response.read().decode("utf-8")
    except Exception:
        result = subprocess.run(
            ["curl", "-skL", url],
            check=True,
            capture_output=True,
            text=True,
        )
        return result.stdout


def fetch_json(url: str) -> object:
    return json.loads(fetch_url(url, timeout=20))


def walk_json(value: object, chars: set[str]) -> None:
    if isinstance(value, str):
        chars.update(value)
    elif isinstance(value, dict):
        for item in value.values():
            walk_json(item, chars)
    elif isinstance(value, list):
        for item in value:
            walk_json(item, chars)


def scan_firmware_ui_chars() -> set[str]:
    chars: set[str] = set()
    for directory in FIRMWARE_SCAN_DIRS:
        if not directory.is_dir():
            continue
        for path in sorted(directory.glob("*")):
            if path.suffix not in {".cpp", ".h"}:
                continue
            for match in STRING_LITERAL_RE.finditer(path.read_text(encoding="utf-8")):
                chars.update(match.group(1))
    return chars


def load_opencc_traditional() -> set[str]:
    chars: set[str] = set()
    for line in fetch_url(OPENCC_ST_URL).splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        for part in parts[1:]:
            chars.update(ch for ch in part if "\u4e00" <= ch <= "\u9fff")
    return chars


def codes_from_chars(chars: set[str]) -> list[int]:
    return sorted({ord(ch) for ch in chars if ord(ch) >= 0x20})


def format_unicode_array(name: str, codes: list[int], comment: str) -> str:
    lines = [f"  0x{code:04X}," for code in codes]
    return (
        f"// {comment}\n"
        f"static final int[] {name} = {{\n"
        + "\n".join(lines)
        + "\n};\n"
    )


def trim_detail_codes(detail_codes: list[int], max_cjk: int = 4200) -> list[int]:
    if len(detail_codes) <= 4500:
        return detail_codes
    non_cjk = [code for code in detail_codes if not (0x4E00 <= code <= 0x9FFF)]
    cjk = [code for code in detail_codes if 0x4E00 <= code <= 0x9FFF][:max_cjk]
    return sorted(set(non_cjk + cjk))


def write_processing_tables(main_codes: list[int], detail_codes: list[int]) -> None:
    large_codes = sorted({ord(ch) for ch in "0123456789-°C"})
    main_header = format_unicode_array(
        "specificUnicodes",
        main_codes,
        "Auto-generated by tools/generate_hko_font_codes.py (10/12)",
    )
    detail_header = format_unicode_array(
        "detailUnicodes",
        detail_codes,
        "Auto-generated detail set for PFTC6 only (HKO + OpenCC traditional)",
    )
    large_header = format_unicode_array(
        "largeUnicodes",
        large_codes,
        "Auto-generated for PFTC18 only (temperature digits)",
    )
    combined = f"{main_header}\n{detail_header}\n{large_header}"

    if not CREATE_FONT_PDE.exists():
        return

    pde = CREATE_FONT_PDE.read_text(encoding="utf-8")
    start = pde.index("static final int[] unicodeBlocks")
    end = pde.index("// >>>>>>>>>> USER CONFIGURED PARAMETERS END HERE")
    replacement = (
        "static final int[] unicodeBlocks = {\n"
        "  0x0021, 0x007E, // ASCII\n"
        "};\n\n"
        f"{combined}\n"
    )
    CREATE_FONT_PDE.write_text(pde[:start] + replacement + pde[end:], encoding="utf-8")


def collect_main_chars(*, offline: bool) -> set[str]:
    chars = set(load_chars_file(COMMON_CHARS_FILE))
    chars.update(scan_firmware_ui_chars())
    if offline:
        return chars

    for data_type in HKO_DATA_TYPES:
        walk_json(fetch_json(f"{HKO_API}?dataType={data_type}&lang=tc"), chars)
    return chars


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--offline",
        action="store_true",
        help="Skip HKO API and OpenCC fetch; use local char files only",
    )
    args = parser.parse_args()

    chars = collect_main_chars(offline=args.offline)
    main_codes = codes_from_chars(chars)

    detail_chars = set(chars)
    detail_chars.update(load_chars_file(DETAIL_CHARS_FILE))
    if not args.offline:
        try:
            opencc = load_opencc_traditional()
            detail_chars.update(opencc)
            print(f"OpenCC traditional characters: {len(opencc)}")
        except Exception as exc:
            print(f"OpenCC fetch failed ({exc}), using local detail file only")

    detail_codes = trim_detail_codes(codes_from_chars(detail_chars))
    write_processing_tables(main_codes, detail_codes)

    extras = "".join(
        sorted(ch for ch in detail_chars if ch not in chars and "\u4e00" <= ch <= "\u9fff")
    )
    DETAIL_CHARS_FILE.write_text(
        "# 6pt 預報詳情擴充常用字（由 OpenCC + 本檔維護；勿手動刪成全字庫）\n"
        f"{extras}\n",
        encoding="utf-8",
    )

    print(f"Main (10/12/18): {len(main_codes)} code points")
    print(f"Detail (6 only): {len(detail_codes)} code points")
    if CREATE_FONT_PDE.exists():
        print(f"Updated {CREATE_FONT_PDE}")


if __name__ == "__main__":
    main()
